import { Post } from "@/types/post";

export const examplePosts: Post[] = [
  {
    id: "1",
    title: "Introducing Legacy Vaults",
    slug: "introducing-legacy-vaults",
    excerpt: "<p>We're excited to launch our secure Legacy Vaults feature!</p>",
    content: "<p>Full content about the new Legacy Vaults feature...</p>",
    isSticky: true,
    date: "2025-06-10T10:00:00",
    featuredImage: {
      node: {
        sourceUrl: "/images/image-tile1.jpg",
      },
    },
    categories: {
      nodes: [{ name: "Updates", slug: "updates" }],
    },
  },
  {
    id: "2",
    title: "Team Retreat Highlights",
    slug: "team-retreat-highlights",
    excerpt: "<p>Here’s what happened during our 2025 team retreat.</p>",
    content: "<p>Details from our amazing team retreat...</p>",
    isSticky: true,
    date: "2025-06-09T14:00:00",
    featuredImage: {
      node: {
        sourceUrl: "/images/image-tile2.jpg",
      },
    },
    categories: {
      nodes: [{ name: "Announcements", slug: "announcements" }],
    },
  },
  {
    id: "3",
    title: "How Aeternum Protects Your Data",
    slug: "data-protection-overview",
    excerpt: "<p>We take your privacy seriously. Here's how.</p>",
    content: "<p>Detailed breakdown of our security measures...</p>",
    isSticky: true,
    date: "2025-06-08T11:30:00",
    featuredImage: {
      node: {
        sourceUrl: "/images/image-tile3.jpg",
      },
    },
    categories: {
      nodes: [{ name: "Security", slug: "security" }],
    },
  },
  {
    id: "4",
    title: "Customer Spotlight: The Lee Family",
    slug: "customer-spotlight-lee",
    excerpt:
      "<p>See how the Lee family uses Aeternum to preserve memories.</p>",
    content: "<p>Full customer story and interview...</p>",
    isSticky: true,
    date: "2025-06-07T09:20:00",
    featuredImage: {
      node: {
        sourceUrl: "/images/image-tile4.jpg",
      },
    },
    categories: {
      nodes: [{ name: "Stories", slug: "stories" }],
    },
  },
  {
    id: "5",
    title: "Version 2.1.0 is Live!",
    slug: "version-2-1-0-release",
    excerpt: "<p>Lots of performance and design improvements!</p>",
    content: "<p>Changelog and new features listed here...</p>",
    isSticky: true,
    date: "2025-06-06T13:45:00",
    featuredImage: {
      node: {
        sourceUrl: "/images/image-tile5.jpg",
      },
    },
    categories: {
      nodes: [{ name: "Updates", slug: "updates" }],
    },
  },
  {
    id: "6",
    title: "Aeternum Joins the Tech for Good Conference",
    slug: "tech-for-good-conference",
    excerpt: "<p>We're honored to participate in this inspiring event.</p>",
    content: "<p>Our talk, booth, and key takeaways...</p>",
    isSticky: true,
    date: "2025-06-05T16:00:00",
    featuredImage: {
      node: {
        sourceUrl: "/images/image-tile6.jpg",
      },
    },
    categories: {
      nodes: [{ name: "Events", slug: "events" }],
    },
  },
  {
    id: "7",
    title: "Memory Capsule Tutorial",
    slug: "memory-capsule-tutorial",
    excerpt: "<p>Step-by-step guide to creating your first memory capsule.</p>",
    content: "<p>How to record, store, and share memories...</p>",
    isSticky: true,
    date: "2025-06-04T08:10:00",
    featuredImage: {
      node: {
        sourceUrl: "/images/image-tile7.jpg",
      },
    },
    categories: {
      nodes: [{ name: "Guides", slug: "guides" }],
    },
  },
  {
    id: "8",
    title: "New Partnership with HeritageApp",
    slug: "partnership-heritageapp",
    excerpt: "<p>We're teaming up to broaden digital preservation access.</p>",
    content: "<p>What this partnership means for users...</p>",
    isSticky: true,
    date: "2025-06-03T17:00:00",
    featuredImage: {
      node: {
        sourceUrl: "/images/image-tile8.jpg",
      },
    },
    categories: {
      nodes: [{ name: "Partnerships", slug: "partnerships" }],
    },
  },
  {
    id: "9",
    title: "Why Digital Legacy Matters",
    slug: "why-digital-legacy-matters",
    excerpt: "<p>A look at why preserving stories matters more than ever.</p>",
    content: "<p>Our mission and the big picture...</p>",
    isSticky: true,
    date: "2025-06-02T12:00:00",
    featuredImage: {
      node: {
        sourceUrl: "/images/image-tile9.jpg",
      },
    },
    categories: {
      nodes: [{ name: "Insights", slug: "insights" }],
    },
  },
  {
    id: "10",
    title: "Q2 Product Roadmap Preview",
    slug: "q2-roadmap-preview",
    excerpt: "<p>Here’s what’s coming in the next few months.</p>",
    content: "<p>Plans, upgrades, and exciting features...</p>",
    isSticky: true,
    date: "2025-06-01T15:30:00",
    featuredImage: {
      node: {
        sourceUrl: "/images/image-tile10.jpg",
      },
    },
    categories: {
      nodes: [{ name: "Roadmap", slug: "roadmap" }],
    },
  },

  {
    id: "11",
    title: "Extra Post 11",
    slug: "extra-post-11",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-21T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile11.jpg" } },
    categories: { nodes: [{ name: "Category1", slug: "category1" }] },
  },
  {
    id: "12",
    title: "Extra Post 12",
    slug: "extra-post-12",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-20T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile12.jpg" } },
    categories: { nodes: [{ name: "Category2", slug: "category2" }] },
  },
  {
    id: "13",
    title: "Extra Post 13",
    slug: "extra-post-13",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-19T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile13.jpg" } },
    categories: { nodes: [{ name: "Category3", slug: "category3" }] },
  },
  {
    id: "14",
    title: "Extra Post 14",
    slug: "extra-post-14",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-18T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile14.jpg" } },
    categories: { nodes: [{ name: "Category4", slug: "category4" }] },
  },
  {
    id: "15",
    title: "Extra Post 15",
    slug: "extra-post-15",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-17T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile15.jpg" } },
    categories: { nodes: [{ name: "Category0", slug: "category0" }] },
  },
  {
    id: "16",
    title: "Extra Post 16",
    slug: "extra-post-16",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-16T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile16.jpg" } },
    categories: { nodes: [{ name: "Category1", slug: "category1" }] },
  },
  {
    id: "17",
    title: "Extra Post 17",
    slug: "extra-post-17",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-15T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile17.jpg" } },
    categories: { nodes: [{ name: "Category2", slug: "category2" }] },
  },
  {
    id: "18",
    title: "Extra Post 18",
    slug: "extra-post-18",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-14T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile18.jpg" } },
    categories: { nodes: [{ name: "Category3", slug: "category3" }] },
  },
  {
    id: "19",
    title: "Extra Post 19",
    slug: "extra-post-19",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-13T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile19.jpg" } },
    categories: { nodes: [{ name: "Category4", slug: "category4" }] },
  },
  {
    id: "20",
    title: "Extra Post 20",
    slug: "extra-post-20",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-12T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile20.jpg" } },
    categories: { nodes: [{ name: "Category0", slug: "category0" }] },
  },
  {
    id: "21",
    title: "Extra Post 21",
    slug: "extra-post-21",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-11T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile21.jpg" } },
    categories: { nodes: [{ name: "Category1", slug: "category1" }] },
  },
  {
    id: "22",
    title: "Extra Post 22",
    slug: "extra-post-22",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-10T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile22.jpg" } },
    categories: { nodes: [{ name: "Category2", slug: "category2" }] },
  },
  {
    id: "23",
    title: "Extra Post 23",
    slug: "extra-post-23",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-09T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile23.jpg" } },
    categories: { nodes: [{ name: "Category3", slug: "category3" }] },
  },
  {
    id: "24",
    title: "Extra Post 24",
    slug: "extra-post-24",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-08T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile24.jpg" } },
    categories: { nodes: [{ name: "Category4", slug: "category4" }] },
  },
  {
    id: "25",
    title: "Extra Post 25",
    slug: "extra-post-25",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-07T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile25.jpg" } },
    categories: { nodes: [{ name: "Category0", slug: "category0" }] },
  },
  {
    id: "26",
    title: "Extra Post 26",
    slug: "extra-post-26",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-06T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile26.jpg" } },
    categories: { nodes: [{ name: "Category1", slug: "category1" }] },
  },
  {
    id: "27",
    title: "Extra Post 27",
    slug: "extra-post-27",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-05T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile27.jpg" } },
    categories: { nodes: [{ name: "Category2", slug: "category2" }] },
  },
  {
    id: "28",
    title: "Extra Post 28",
    slug: "extra-post-28",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-04T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile28.jpg" } },
    categories: { nodes: [{ name: "Category3", slug: "category3" }] },
  },
  {
    id: "29",
    title: "Extra Post 29",
    slug: "extra-post-29",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-03T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile29.jpg" } },
    categories: { nodes: [{ name: "Category4", slug: "category4" }] },
  },
  {
    id: "30",
    title: "Extra Post 30",
    slug: "extra-post-30",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-02T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile30.jpg" } },
    categories: { nodes: [{ name: "Category0", slug: "category0" }] },
  },
  {
    id: "31",
    title: "Extra Post 31",
    slug: "extra-post-31",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-05-01T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile31.jpg" } },
    categories: { nodes: [{ name: "Category1", slug: "category1" }] },
  },
  {
    id: "32",
    title: "Extra Post 32",
    slug: "extra-post-32",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-04-30T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile32.jpg" } },
    categories: { nodes: [{ name: "Category2", slug: "category2" }] },
  },
  {
    id: "33",
    title: "Extra Post 33",
    slug: "extra-post-33",
    excerpt: "<p>This is a sample excerpt.</p>",
    content: "<p>This is the full sample content.</p>",
    isSticky: true,
    date: "2025-04-29T12:00:00",
    featuredImage: { node: { sourceUrl: "/images/image-tile33.jpg" } },
    categories: { nodes: [{ name: "Category3", slug: "category3" }] },
  },
];
